[build]
  command = "npm run build"
  publish = "frontend/next-jam/out"

[context.deploy-preview]
  command = "npm run build:preview"

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"