[build]
  command = "npm run export"
  publish = "frontend/next-jam/out"

[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"